Repository acquia/acquia_cms, pull requests merged in 2021-06, with the labels that each got.

#825 ACMS-787: Add Slack notifications for Travis build failures.
  .travis.yml
Labels: Minor change

#837 ACMS-809: Update Acquia Search to 3.0.3.
  composer.json
  composer.lock
Labels: dependencies

#842 ACMS-810: Fix Content Hub UI broken and blank in ACMS
  modules/acquia_cms_toolbar/acquia_cms_toolbar.module
  modules/acquia_cms_toolbar/js/acms_toolbar.js
Labels: bug
